use bookstore;

INSERT INTO publishinghouse(name, email) VALUES ("Prestel Publishing","prestelpublishing@mail.com")
INSERT INTO publishinghouse(name, email) VALUES ("Phaidon ","phaidon @mail.com")
INSERT INTO publishinghouse(name, email) VALUES ("Taschen","taschen@mail.com")
INSERT INTO publishinghouse(name, email) VALUES ("teNeues","teNeues@mail.com")
INSERT INTO publishinghouse(name, email) VALUES ("Penguin Random House","penguinRandomHouse@mail.com")
INSERT INTO publishinghouse(name, email) VALUES ("Gallimard","gallimard@mail.com")

INSERT INTO isbn(code) VALUES ("1234567893574")
INSERT INTO isbn(code) VALUES ("9876543215987")
INSERT INTO isbn(code) VALUES ("3216549874523")
INSERT INTO isbn(code) VALUES ("7896541235479")
INSERT INTO isbn(code) VALUES ("9871234568524")
INSERT INTO isbn(code) VALUES ("6543219871423")
INSERT INTO isbn(code) VALUES ("2135846794236")
INSERT INTO isbn(code) VALUES ("4567891236874")
INSERT INTO isbn(code) VALUES ("5462138974236")
INSERT INTO isbn(code) VALUES ("8794563215698")
INSERT INTO isbn(code) VALUES ("9638527416549")
INSERT INTO isbn(code) VALUES ("1238527416549")
INSERT INTO isbn(code) VALUES ("4718527416549")
INSERT INTO isbn(code) VALUES ("8123527416549")
INSERT INTO isbn(code) VALUES ("2798527416549")


INSERT INTO author(firstName, lastName) VALUES ("Christina", "Végh")
INSERT INTO author(firstName, lastName) VALUES ("Philipp", "Kaiser")
INSERT INTO author(firstName, lastName) VALUES ("Jesse", "Simon")
INSERT INTO author(firstName, lastName) VALUES ("Hans Werner", "Holzwarth")
INSERT INTO author(firstName, lastName) VALUES ("Monty", "Don")
INSERT INTO author(firstName, lastName) VALUES ("Jim", "Naughten")
INSERT INTO author(firstName, lastName) VALUES ("Jonathan", "Torgovnik")
INSERT INTO author(firstName, lastName) VALUES ("Paul", "Duncan")
INSERT INTO author(firstName, lastName) VALUES ("Vincent", "Lagrange")
INSERT INTO author(firstName, lastName) VALUES ("Jennifer S.", "Holland ")
INSERT INTO author(firstName, lastName) VALUES ("ÉRIC", "FOTTORINO")
INSERT INTO author(firstName, lastName) VALUES ("Bernard", "Benoliel")
INSERT INTO author(firstName, lastName) VALUES ("Serge", "Ramellis")
INSERT INTO author(firstName, lastName) VALUES ("Hélène", "Kérillis")
INSERT INTO author(firstName, lastName) VALUES ("Peter ", "Lindbergh")
INSERT INTO author(firstName, lastName) VALUES ("Sylvain", "Prudhomme")

INSERT INTO discount(discount, startDate, endDate) VALUES (15,"2021-01-15", "2021-02-15")
INSERT INTO discount(discount, startDate, endDate) VALUES (25,"2021-01-15", "2021-02-15")
INSERT INTO discount(discount, startDate, endDate) VALUES (35,"2021-01-15", "2021-02-15")
INSERT INTO discount(discount, startDate, endDate) VALUES (65,"2021-01-15", "2021-02-15")
INSERT INTO discount(discount, startDate, endDate) VALUES (15,"2021-01-15", "2021-02-15")
INSERT INTO discount(discount, startDate, endDate) VALUES (15,"2021-01-15", "2021-02-15")
INSERT INTO discount(discount, startDate, endDate) VALUES (15,"2021-01-15", "2021-02-15")
INSERT INTO discount(discount, startDate, endDate) VALUES (15,"2021-01-15", "2021-02-15")
INSERT INTO discount(discount, startDate, endDate) VALUES (15,"2021-01-15", "2021-02-15")
INSERT INTO discount(discount, startDate, endDate) VALUES (15,"2021-01-15", "2021-02-15")
INSERT INTO discount(discount, startDate, endDate) VALUES (15,"2021-01-15", "2021-02-15")
INSERT INTO discount(discount, startDate, endDate) VALUES (15,"2021-01-15", "2021-02-15")
INSERT INTO discount(discount, startDate, endDate) VALUES (15,"2021-01-15", "2021-02-15")
INSERT INTO discount(discount, startDate, endDate) VALUES (15,"2021-01-15", "2021-02-15")
INSERT INTO discount(discount, startDate, endDate) VALUES (15,"2021-01-15", "2021-02-15")

INSERT INTO book( name, bookgenre, pages, price, book_format, isbn_id, publishinghouse_id, stock) VALUES ("Where Art Might Happen", 4, 120, 15.5, "PB", 1, 5, 123)
INSERT INTO book( name, bookGenre, pages, price, book_format, isbn_id, publishinghouse_id, stock) VALUES ("Berlin Typography", 4, 130, 16.5, "HB", 2, 4, 132)
INSERT INTO book( name, bookGenre, pages, price, book_format, isbn_id, publishinghouse_id, stock) VALUES ("David Hockney. A Chronology.", 4, 140, 17.5, "AB", 3, 3, 5)
INSERT INTO book( name, bookGenre, pages, price, book_format, isbn_id, publishinghouse_id, stock) VALUES ("Basquiat", 4, 150, 18.5, "KE", 4, 2, 7)
INSERT INTO book( name, bookGenre, pages, price, book_format, isbn_id, publishinghouse_id, stock) VALUES ("American Gardens", 5, 160, 19.5, "EB", 5, 1, 9)
INSERT INTO book( name, bookGenre, pages, price, book_format, isbn_id, publishinghouse_id, stock) VALUES ("Animal Kingdom", 4, 170, 22.5, "HB", 6, 1, 23)
INSERT INTO book( name, bookGenre, pages, price, book_format, isbn_id, publishinghouse_id, stock) VALUES ("Bollywood Dreams", 4, 180, 29.5, "KE", 7, 2, 14)
INSERT INTO book( name, bookGenre, pages, price, book_format, isbn_id, publishinghouse_id, stock) VALUES ("The Star Wars Archives. 1999–2005", 4, 180, 29.5, "PB",  8, 3, 12)
INSERT INTO book( name, bookGenre, pages, price, book_format, isbn_id, publishinghouse_id, stock) VALUES ("The Dogs", 4, 180, 29.5, "AB", 9, 4, 19)
INSERT INTO book( name, bookGenre, pages, price, book_format, isbn_id, publishinghouse_id, stock) VALUES ("Marina A.", 3, 180, 29.5, "EB", 10, 6, 21)
INSERT INTO book( name, bookGenre, pages, price, book_format, isbn_id, publishinghouse_id, stock) VALUES ("Clint Eastwood", 3,  180, 29.5, "PB", 11, 2, 23)
INSERT INTO book( name, bookGenre, pages, price, book_format, isbn_id, publishinghouse_id, stock) VALUES ("Barcelona ", 1,  180, 29.5,  "HB", 12, 4, 24)
INSERT INTO book( name, bookGenre, pages, price, book_format, isbn_id, publishinghouse_id, stock) VALUES ("A Bird in Winter", 6,  180, 29.5, "AB", 13, 1, 41)
INSERT INTO book( name, bookGenre, pages, price, book_format, isbn_id, publishinghouse_id, stock) VALUES ("On Fashion Photography", 4, 180, 29.5, "KE", 14, 3, 33)
INSERT INTO book( name, bookGenre, pages, price, book_format, isbn_id, publishinghouse_id, stock) VALUES ("Les orages", 0, 180, 29.5, "EB", 15, 6, 87)

insert into author_book (author_id, book_id) values (1, 1)
insert into author_book (author_id, book_id) values (2, 1)
insert into author_book (author_id, book_id) values (3, 2)
insert into author_book (author_id, book_id) values (4, 3)
insert into author_book (author_id, book_id) values (4, 4)
insert into author_book (author_id, book_id) values (5, 5)
insert into author_book (author_id, book_id) values (6, 6)
insert into author_book (author_id, book_id) values (7, 7)
insert into author_book (author_id, book_id) values (8, 8)
insert into author_book (author_id, book_id) values (9, 9)
insert into author_book (author_id, book_id) values (10, 9)
insert into author_book (author_id, book_id) values (11, 10)
insert into author_book (author_id, book_id) values (12, 11)
insert into author_book (author_id, book_id) values (13, 12)
insert into author_book (author_id, book_id) values (14, 13)
insert into author_book (author_id, book_id) values (15, 14)
insert into author_book (author_id, book_id) values (16, 15)